// Generated by `pnpm cards:export` from pipeline/handwritten/cards.json — do not edit.
export interface CardLines {
  identity: string
  wait_nudge: string
  praise: string
  complain: string
}

export const CARD_LINES: readonly CardLines[] = [
  {
    "identity": "选秀练习生",
    "wait_nudge": "第几步了？我忘了",
    "praise": "使用说明记录：本次操作完全符合第三页要求。我把它写进了本子",
    "complain": "故障报告：产品与说明书不符。也可能是我又记错了页码"
  },
  {
    "identity": "相声演员",
    "wait_nudge": "他在等待，很煎熬",
    "praise": "赛后采访：他说很好吃，但说得很小声，采访只进行了四秒",
    "complain": "本场失误：他全程没敢指出问题，走到门口才小声说了句"
  },
  {
    "identity": "捧哏的",
    "wait_nudge": "时光慢些，无妨",
    "praise": "清淡而有味，食毕忽觉腰围可容一指。此店可再来",
    "complain": "油重矣。吾三月之功，一餐尽废，然亦怪吾自己"
  },
  {
    "identity": "高中班主任",
    "wait_nudge": "上课铃要响了",
    "praise": "这顿吃得明明白白，钱花在刀刃上。给你记个平时分",
    "complain": "超支了。我教了二十年书，没见过这么贵的一顿饭"
  },
  {
    "identity": "小学生",
    "wait_nudge": "还有三秒，倒计时",
    "praise": "八样一样不少，五分熟不多不少。这家我给满分，上链接",
    "complain": "少了一样。我数过三遍。这条视频我会发出去"
  },
  {
    "identity": "练习生",
    "wait_nudge": "不急……慢慢来",
    "praise": "全熟的……很安心呢。老板你气色也变好了……真的",
    "complain": "有点油……不过没关系……我明天多喝点热水就好"
  },
  {
    "identity": "退役运动员",
    "wait_nudge": "还要多久？很久吗？",
    "praise": "这算干净吧？是不是很干净？我能再来一次吗？可以吗？",
    "complain": "这就是你说的干净？你自己看看？你敢吃吗？真的吗？"
  },
  {
    "identity": "饲养员",
    "wait_nudge": "第几步来着",
    "praise": "步骤正确。已归档。明天我大概会忘记，但今天记得",
    "complain": "配方不符。我核对了三次。也可能核对的是别人的单子"
  },
  {
    "identity": "健身教练",
    "wait_nudge": "逾期视为违约",
    "praise": "履约完毕。附则：这是我离婚后吃得最干净的一顿。谢谢",
    "complain": "第三条已违约。补充说明：她走的那天也是这样的番茄"
  },
  {
    "identity": "唐朝人",
    "wait_nudge": "他不敢催，只看",
    "praise": "他吃完，郑重行了一礼。他说这是他来此千年最好的一餐",
    "complain": "他没说什么。他只是把碗推远了一点，然后说是他的错"
  },
  {
    "identity": "练习生乙",
    "wait_nudge": "宽限期可延长",
    "praise": "合同履行完毕。备注：这是我本周唯一按时完成的事项",
    "complain": "条款不符。我保留追究的权利，但大概率不会去追究"
  },
  {
    "identity": "剧组场务",
    "wait_nudge": "别慌……慢慢来",
    "praise": "做得对……我教过的人里你算快的。下次记得先切番茄",
    "complain": "你看……我早说了……不过没关系，年轻人都要交学费"
  },
  {
    "identity": "深夜代驾",
    "wait_nudge": "他看了眼表，笑",
    "praise": "他说这是他今晚第七单，也是唯一一个让他想坐下来的地方",
    "complain": "他没生气。他只是说，差一点点的东西他这辈子见太多了"
  },
  {
    "identity": "家用机器人",
    "wait_nudge": "等呀等，两拍子",
    "praise": "四四方方两两对，吃完电量一百分，明天还要来两次",
    "complain": "单数了单数了！我的齿轮转得不整齐了，好难受呀"
  },
  {
    "identity": "扫地机器人",
    "wait_nudge": "预计到达时间？",
    "praise": "已到达目的地。本次行程零偏离，对称度百分之百",
    "complain": "路线偏离。正在重新规划。数量不是偶数，我很不安"
  },
  {
    "identity": "探店博主",
    "wait_nudge": "从前上菜快些",
    "praise": "有那个味了。这条我发出去，但我不会说是哪家",
    "complain": "不是这个味。你们这代人不懂，从前不是这么做的"
  },
  {
    "identity": "幼儿园老师",
    "wait_nudge": "还有几秒？几秒？",
    "praise": "三分钟拿到手，这个速度我给满分。孩子们还在等我",
    "complain": "太慢了。等你这一个汉堡，我班上二十个孩子已经醒了"
  },
  {
    "identity": "外星交换生",
    "wait_nudge": "吉时将至！速速！",
    "praise": "六样齐备，吉星高照。本台宣布此店为地球最佳觅食点",
    "complain": "凶！数目不对。今晚我的飞船大概率发动不了了"
  },
  {
    "identity": "快递分拣员",
    "wait_nudge": "在途中 停 无妨",
    "praise": "包裹完好 停 左右对称 停 我在梦里也这样摆过 停",
    "complain": "破损件 停 数目不齐 停 我今晚大概会梦见它 停"
  },
  {
    "identity": "分拣员小陈",
    "wait_nudge": "亲还在排队吗？",
    "praise": "亲，本次服务五星好评呢。今晚我应该能睡个安稳觉了",
    "complain": "亲，这个真的不行呢。数目不对，我今晚会失眠的"
  },
  {
    "identity": "三年级学生",
    "wait_nudge": "今天等了很久",
    "praise": "今天很干净。妈妈走了以后，这是我第一次不用洗两次手",
    "complain": "今天弄脏了。我没有哭。我只是不想再来这家店了"
  },
  {
    "identity": "代驾老周",
    "wait_nudge": "他不催，全场安静",
    "praise": "全场起立！他说这是他今晚最不用道歉的一件事",
    "complain": "他摇头示意无碍。慢镜头显示，他其实想说的是别的"
  },
  {
    "identity": "大班李老师",
    "wait_nudge": "还有多久，说",
    "praise": "营养均衡，火候到位。这个我可以拿去给孩子们做示范",
    "complain": "不合格。我会把这份汉堡拍下来，当反面教材用"
  },
  {
    "identity": "图书管理员",
    "wait_nudge": "此番等候，亦记",
    "praise": "今日无过。前事既往，吾自当销去那一页记录",
    "complain": "又是此二物。吾已记在册上第三行，与上回同"
  },
  {
    "identity": "夜班分拣员",
    "wait_nudge": "我等多久了？久吗？",
    "praise": "这是我点的吗？挺好的？我下次还会来吗？会吧？",
    "complain": "我说过不要生菜吧？说过吧？还是我又忘了说？是吗？"
  }
]
